### PR TITLE
Remove use of each(), which is removed in PHP 8

### PR DESCRIPTION
**Pull request by nikic**
each() is deprecated since PHP 7.2 and removed entirely in PHP 8, so make sure we don't use it.

### CODE REVIEW

**Comment by nikic** [comment]
Ping. I'd like to restore availability of PHP nightly builds on Travis, and this is the current blocker.

**Comment by ashnazg** [comment]
@nikic, does your build use this from a GitHub branch, or is it pulling an actual PEAR package release tarball?

**Comment by nikic** [comment]
The build uses PEAR package releases.

**Comment by ashnazg** [comment]
Hmm, so then you need this PR merged, a release done on PEAR, and the PEAR channel available for the installation download. The last two won't be feasible until we get pear.php.net back online.

**Comment by nikic** [comment]
@ashnazg Ah, I'm actually referring to the PEAR phars here (which depend on this package). Availability of pear.php.net is not strictly necessary, just the availability of the phar (currently downloaded from GitHub).

**Comment by ashnazg** [comment]
@nikic ok, I'm thinking you mean the `install-pear-nozlib.phar` [here](https://github.com/pear/pearweb_phars), which contains a Console_Getopt release inside it.

Let me see what I can do for this...

**Comment by ashnazg** [comment]
@nikic updated phar files are now [available](https://github.com/pear/pearweb_phars).

**Comment by nikic** [comment]
@ashnazg Thanks! Build is green now on https://github.com/travis-ci/php-src-builder/pull/28, hopefully we'll get new nightlies soon :)

**Comment by torinaki** [comment]
@nikic it is not the only depreciation issue:
```
Fatal error: Uncaught Error: Call to undefined function create_function() in phar:///usr/src/php/pear/install-pear-nozlib.phar/PEAR/Registry.php:2067
Stack trace:
#0 phar:///usr/src/php/pear/install-pear-nozlib.phar/PEAR/Installer.php(1182): PEAR_Registry->checkFileMap(Array, 'Archive_Tar', '1.1')
#1 phar:///usr/src/php/pear/install-pear-nozlib.phar/index.php(318): PEAR_Installer->install('phar://install-...', Array)
#2 /usr/src/php/pear/install-pear-nozlib.phar(1271): require_once('phar:///usr/src...')
#3 {main}
  thrown in phar:///usr/src/php/pear/install-pear-nozlib.phar/PEAR/Registry.php on line 2067
```

**Comment by nikic** [comment]
@torinaki I'm on it. I only checked that the build works, but when I run the PEAR test suite there are many issues. I'll try to fix everything.

**Pull request merged**
